name: CD Front-end

on:
  schedule:
    - cron: '* 23 * * *'
  workflow_dispatch:
jobs:
  ci:
    name: CI Workflow Main
    uses: ./.github/workflows/ci-frontend-main.yml
    
  deploy:
    needs: ci
    runs-on: ubuntu-latest
    name: Deploy Railway
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: 
          node-version: 16
      - name: Instalação do cliente Railway
        run: npm install -g @railway/cli  
      - name: Instalação do cliente Angular CLI
        run: npm install -g @angular/cli
      - name: Deploy
        working-directory: front-end/dist/
        run: railway up --detach --service sgcm-jonatan2
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
