name: CI - DEPLOY - Front-end

on:
  push:
    branches:
      - 'main'
    paths:
      - 'front-end/**'
  pull_request:
    paths:
      - 'front-end/**'   
  workflow_dispatch:    
  
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up NODE 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
            
      - name: instalando dependencias
        working-directory: front-end/
        run: npm install
      - name: Test
        working-directory: front-end/
        run: npm test -- --no-watch --no-progress --browsers=ChromeHeadlessCI

      - name: Package
        working-directory: front-end/
        run: npm run build --prod
      - name: Instalação do cliente Railway
        run: npm install -g @railway/cli  
      - name: Deploy
        working-directory: front-end/dist/sgcmapp
        run: railway up --detach --service sgcm-jonatan2
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
